language: node_js
node_js:
- '4'
- '5'
- '6'
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
script:
- npm test
before_deploy:
- npm run compile
deploy:
  provider: npm
  email: dancrumb@gmail.com
  on:
    tags: true
    repo: dancrumb/expiry-timer
  api_key:
    secure: G7hwSUSLcRd/64YqZVpS/8l0T+eQ1uGbU50uMIlOiw5cjjbHF60/Xju7CrNUhIbQiG+Lc+zRQMiTXFQNYuroxPoulFR8RlzRlhDvZf22DCtoCVWfJcb/4kEwilCweo+DvuROlpEMbU4P7ZZuwcpZ9X+xPEP6VEY35Zxz/gsuudX8n2XZtLKptGBsTqzg7pNnLuk+wnV0OemZRwZI+jRs5tx3pC2SUhxr8hJmJnXjhUoZqhDgqlhOHB8eC3PwO6DX25kfU7+CBbDL3Uf6fxP4jl+DuVCTD67VFTWtV8c6aTkLkRzHmh0tHz+XmFxh3zP7PPP4sjTDRM46ubLD10gX8qlY3MKQ8NG5TVxgz7EvWQGLLf6bnYaP7w9+GegkObcKfph40y54XR55qOZyTM0Yde0xa4o3QnXeCzMMHHZNAyLCxc8XMkHynYPZbJjy7sCfaZTxaOXavgYIY+DHnZUNjlTaxkt2jejwGtP2/vE/MQfwlDS63/smrNB9PnYUbYgnuSBzmuYNlY7ycxzqYONbw7p9oISesqru3vT2PpjintONBcpoy+ZMX7SPOnzr/wsVBzG2I1ByBcsd+MZJb51lV9lFCh+XSwgIt1FgCwfXw/eROgSQailTiDxxwC8sn64S0Pr0MBEHwdKrExwwQDUricnGF2aNF3K4+HVrA838ibc=
